### ISSUE TITLE
Date mismatch between ground station and WMS causes a layer to not load as expected

### ISSUE THREAD

**Issue by dubwalla** [WFP-VAM/prism-frontend#116]
I just deployed the ground station date fix to https://prism-mongolia.org/. After deploying I noticed that if you load a ground station layer first (which as of now will use Sept-21 as the latest) and then try to load a WMS layer, it fails. The latest WMS layer is Sept-11.

**Comment by ericboucher** [comment]
@SimplyBallistic short term, could we have a warning when this happens and invite to select a new date?

Otherwise it just silently fails to load the layer.

**Comment by SimplyBallistic** [comment]
> @SimplyBallistic short term, could we have a warning when this happens and invite to select a new date?
> 
> Otherwise it just silently fails to load the layer.

Sure, I'll add it as a notification similar to this: https://github.com/WFP-VAM/prism-frontend/blob/master/src/components/MapView/index.tsx#L152
