### ISSUE TITLE
Dev Server not working

### ISSUE THREAD

**Issue by khattakdev** [WFP-VAM/prism-frontend#119]
Hey 👋 
I am facing some issues in setting up a local environment.Since there isn't any Contribution guide, so I am not sure whether did I miss something or it's a bug somewhere (dependencies versions most probably)
I cloned the repo and install dependencies, without any configuration to the files I tried starting the dev server but I end up with some eslint plugin issue
![image](https://user-images.githubusercontent.com/37709578/101525933-cf00e580-39ad-11eb-8fc7-00fed1446f6d.png)
Google wasn't a good help in this case, so maybe someone who already faced a similar issue might be able to help me.

<details>
<summary>List of commands I used:</summary>

```
git clone https://github.com/WFP-VAM/prism-frontend.git --depth=1
cd .\prism-frontend\
npm install
npm start
```

</details>

**Comment by ericboucher** [comment]
Hi @khattakdev, thanks for your report. Have you tried using `yarn`? The project has been set up using yarn and a `yarn.lock` is available.

That should help make sure that your environment gets started with the correct versions. Please do let us know if that does not work.

**Comment by khattakdev** [comment]
I've tried both yarn and npm, nothing works for me. Both are giving the
same errors.

**Comment by SimplyBallistic** [comment]
what's your OS? I I know I faced issues since `EXTEND_ESLINT=true` was not being set on windows, but `cross-env` should solve this. Maybe you can try set it globally in your OS and see if the issue persists?

**Comment by khattakdev** [comment]
Thanks to @SimplyBallistic , the issue has been fixed.

Here are the steps (for Windows Users)
```
git clone https://github.com/WFP-VAM/prism-frontend.git --depth=1
cd .\prism-frontend\
yarn
yarn lint
yarn start
```
