### ISSUE TITLE
Localization of full UI

### ISSUE THREAD

**Issue by dubwalla** [WFP-VAM/prism-frontend#125]
The full user interface for PRISM needs to be able to be easily localized. The configuration process should allow for the creation of alternate labels and text for every element in the UI along with the ability to toggle between language options

**Comment by mwarizmiwafiq** [comment]
For consideration CMV App utilize https://www.npmjs.com/package/i18n where they could setup configurable for string user interface and layers (https://github.com/cmv/cmv-app/tree/develop/viewer/js/config/nls) and support change between language.

**Comment by dubwalla** [comment]
Duplicate of https://github.com/WFP-VAM/prism-frontend/issues/97. Closing this issue
