### ISSUE TITLE
Add support for full timestamp on WMS layers

### ISSUE THREAD

**Issue by dubwalla** [WFP-VAM/prism-frontend#128]
PRISM will soon integrate data on tropical storms and earthquakes. Both of these hazards require full timestamp support. Currently, PRISM only supports YYYY-MM-DD. 

As an example, a layer from WFP's ADAM (accessed through GeoNode WMS - https://geonode.wfp.org/geoserver/prism/wms?request=GetCapabilities) includes the following time format: 2021-01-09T00:00:00.000Z. Future outputs would include the fully formed hour, minute, seconds.

While addressing this issue, we should also look into potentially replacing Moment.js as noted here: https://momentjs.com/docs/

**Comment by mwarizmiwafiq** [comment]
Hi Amit. Yes while we're on it, I think we also need to agree on the standard of handling datetime "available data" in frontend. One of suggestion from @reed1 is to use EPOCH data format as example in this request to get available date for impact layer in PRISM https://vampire.idn.wfp.org/home/get_date/25?start=%22&end=2020-01-01.

You see, that only return set of time array in epoch format. We also need to agree on how we standardize the JSON format as this also will effect on how we handle the timeseries socio-economic data. Please advise @dubwalla. Thank you.

**Comment by dubwalla** [comment]
@ericboucher - thoughts on this issue and input from wafiq?

**Comment by dubwalla** [comment]
@JorgeMartinezG - I think this can be closed via https://github.com/WFP-VAM/prism-frontend/pull/132. Is that correct?

**Comment by dubwalla** [comment]
Addressed via https://github.com/WFP-VAM/prism-frontend/pull/132
