### ISSUE TITLE
Fetch the first valid date for a layer within a month

### ISSUE THREAD

**Issue by dubwalla** [WFP-VAM/prism-frontend#153]
Currently, when a user clicks on a month, it requests a layer for the first day of the month. If a tropical storm happens on a day besides the first of the month, clicking on a month results in the mismatched date popup alert. We should modify this so that when a user clicks on a month in the timeline navigation or loads a new hazard layer, the selected layer is displayed for the first event within that month.

For example, if a tropical storm occurred on 23-Jan-2021, and a user clicks on the month, or toggles the layer on, we should fetch the storm on 23-January instead of 1-January.
<img width="1422" alt="Screen Shot 2021-04-07 at 13 47 44" src="https://user-images.githubusercontent.com/3343536/113931925-e7d8a680-97a7-11eb-9d1d-50df427f8a56.png">

**Comment by JorgeMartinezG** [comment]
IMO we could preserve current behavior within the project. One idea is to have within the prism.json configuration file an option like **dateNotFoundAction** with values such as _use-latest_ or _notify_. What do you think @dubwalla and @ericboucher ?

**Comment by dubwalla** [comment]
I'm ok with making this a configuration option. I am not really convinced there are use cases where we'd want to notify rather than just load the latest. @ericboucher - what do you think about this approach?
