### ISSUE TITLE
Allow for varying symbology in the legend

### ISSUE THREAD

**Issue by dubwalla** [WFP-VAM/prism-frontend#156]
The new layers we are working with for ADAM integration (earthquakes, storm paths, storm nodes, and storm wind buffers) use different symbology than the layers we've used to date. We need a mechanism to add additional symbology options and/or to simply fetch the legend from a WMS service and display within the legend context of PRISM.

See screenshot of an example from the ADAM dashboard (https://gis.wfp.org/adam/):
<img width="1417" alt="Screen Shot 2021-04-13 at 13 17 20" src="https://user-images.githubusercontent.com/3343536/114615524-a8540380-9c5a-11eb-8f05-16ad775a6247.png">

**Comment by dubwalla** [comment]
@JorgeMartinezG - here is some text for the legend for the tropical storm layers. I wasn't able to find these details readily on the GDACS site, so this needs to be validated. But let's use this for now:

- "Tropical storm wind buffers (radii) estimate the potential wind speeds along the path of a storm with a buffer estimating the area exposed to various wind speed categories. This estimate is produced by the Joint Typhoon Warning Center (JTWC) and made available through the Global Disaster Alert and Coordination System (GDACS). More information can be found at https://www.gdacs.org/"
- Tropical storm nodes visualize the estimated maximum wind speed along the storm's path at various points in time. This estimate is produced by the Joint Typhoon Warning Center (JTWC) and made available through the Global Disaster Alert and Coordination System (GDACS). More information can be found at https://www.gdacs.org/"
- Tropical storm tracks visualize the projected path of a storm as shown, based on the forecasted position of the center of a storm  at various points in time. This estimate is produced by the Joint Typhoon Warning Center (JTWC) and made available through the Global Disaster Alert and Coordination System (GDACS). More information can be found at https://www.gdacs.org/"

**Comment by JorgeMartinezG** [comment]
@dubwalla it looks like prism, currently does not support url embedding. Does it needed to be added within this issue or addressed in a new one? Also, at UX level, it looks like it is too much information within the legend divs.

![image](https://user-images.githubusercontent.com/3285923/115873252-53597f80-a408-11eb-9710-a7dd8957351a.png)

**Comment by dubwalla** [comment]
As discussed Jorge, let's simplify the text in the legend area and create a popup with more details. See issue https://github.com/WFP-VAM/prism-frontend/issues/172 for the popup and https://github.com/WFP-VAM/prism-frontend/issues/171 regarding html / markdown support

For these three layers, please use the following text:
- "Wind buffers (radii) estimate potential wind speeds along the path of a storm with a buffer estimating the area exposed to each wind speed category. Produced by the Joint Typhoon Warning Center (JTWC) and made available https://www.gdacs.org/"
- Nodes visualize estimated maximum wind speed along a storm's path at various points in time. Produced by the Joint Typhoon Warning Center (JTWC) and made available https://www.gdacs.org/"
- Tracks visualize the projected path of a storm based on the forecasted position of it's center at various points in time. Produced by the Joint Typhoon Warning Center (JTWC) and made available https://www.gdacs.org/"
