### ISSUE TITLE
A group of layers needs independent attributes from its individual layers

### ISSUE THREAD

**Issue by dubwalla** [WFP-VAM/prism-frontend#157]
A group of layers needs a title and legend description that is separate from the individual layers. For example, ADAM tropical storms are comprised of three layers: storm tracks, storm nodes, and storm wind buffers. The group title which appears in the navigation menu to toggle the group on/off should be 'Tropical storms'. Once the group is active, the legend should show the three independent layers to reflect their individual symbology.

**Comment by ericboucher** [comment]
Addressed in #161
