### ISSUE TITLE
Stats API enhancement - intersect / overlay analysis 

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-frontend#159]
The analysis we've done so far using the stats API is based on raster data and zonal statistics given a polygon (admin boundaries). With new types of hazards (storms and earthquakes), the hazard data layer will be vector data, not raster. For an impact analysis on this type of data, we need to create an additional analysis based on the intersection of the storm or earthquake polygon and the vulnerability layer (also a polygon). 

See ESRI's documentation on intersect analysis: https://pro.arcgis.com/en/pro-app/latest/tool-reference/analysis/intersect.htm

And GeoPandas docs on overlay: https://geopandas.org/docs/user_guide/set_operations.html 

The typical analysis for earthquakes and storms is to determine the number of people exposed to the varying levels of the hazard. I.e., how many people are exposed to magnitude 6.0, 5.5, 5.0, etc for a given earthquake shakemap:
https://earthquake.usgs.gov/earthquakes/eventpage/us6000e1bu/map

For storms, how many people are exposed to 60 km/h, 90 km/h, and 120 km/h winds? https://gis.wfp.org/adam/outputs/ADAM_TS_1000639_8_pop_estimations.pdf

**Comment by dubwalla** [comment]
Gridded population data for Myanmar has been added to ODC's OWS. See layer 'wp_pop_cicunadj'. The data is scaled by 10 and rounded to the next integer. The data is in uint32

**Comment by dubwalla** [comment]
> Gridded population data for Myanmar has been added to ODC's OWS. See layer 'wp_pop_cicunadj'. The data is scaled by 10 and rounded to the next integer. The data is in uint32

@JorgeMartinezG - I just was reminded of the scaling applied to the gridded population data that will need to be managed in the layer config. See wcsConfig in https://github.com/WFP-VAM/prism-frontend/blob/master/src/config/mongolia/layers.json for an example of how this is done

**Comment by wadhwamatic** [comment]
This has been addressed for tropical storms through https://github.com/WFP-VAM/prism-frontend/pull/192 and https://github.com/WFP-VAM/prism-frontend/pull/186
