### ISSUE TITLE
Make map style including basemap configurable

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-frontend#169]
Currently, all PRISM deployments are hard-coded to use the same basemap and style configuration. Going forward, we need flexibility for each deployment to choose their basemap and apply styles as needed.

Specifically, we should allow for the specification of a style within the prism.json config file. 

For reference, in components/MapView/index.tsx, we define the style based on a Mapbox studio style: style="mapbox://styles/eric-ovio/ckaoo00yp0woy1ipevzqnvwzi"

If possible, it would also be preferable to allow users to create the full style document **without** having to create a Mapbox account, and then create the style within Mapbox Studio. See: https://docs.mapbox.com/mapbox-gl-js/style-spec/

**Comment by ericboucher** [comment]
Note that after #362 it will be possible to provide a maplibre style as an environment variable.
