### ISSUE TITLE
Add parameters to limit the level of zooming and panning by a user

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-frontend#179]
The display of some hazard products will need to be configured at the country level. For example, the amount of rainfall and the corresponding categories used in the legend will be very different in arid countries compared to more tropical countries. But a user can currently see the same visualization across the globe by zooming out and/or panning around.

We need to add an upper limit to how far out a user can zoom and boundaries in each direction (north, west, south, east) to limit how far a user can pan. This should be an optional configuration choice, and Ideally a part of the 'map' configuration within prism.json.

**Comment by reed1** [comment]
@wadhwamatic This should be straightforward to implement as mapbox-gl provides the interface.

I added 
```const maxBounds = get(appConfig.map, 'maxBounds');
const maxZoom = get(appConfig.map, 'maxZoom');
if (maxBounds) {
  map.setMaxBounds(maxBounds);
}
if (maxZoom) {
  map.setMaxZoom(maxZoom);
}
```
on the map callback. I tried adding those properties on MapboxMap props but it doesn't work, maybe ReactMapboxGl needs some adjustments.

The config for map: 
```
"map": {
  "latitude": 12.058,
  "longitude": 105.281,
  "zoom": 6.49,
  "maxBounds": [101.070557,9.160099,108.837889,15.566551],
  "maxZoom": 9
},
```

Deployment: [here](https://prism-r1.surge.sh/?hazardLayerId=hydra_s1&date=2022-04-16). I can make PR if required.

**Comment by wadhwamatic** [comment]
Thanks @reed1. It looks like this works for MapLibre as well. Reminder that we've shifted away from Mapbox.. 

Yes, please create a PR so that this can be tested and reviewed.
