### ISSUE TITLE
Attempts to run an analysis or alert for storm data fails with a CORS error

### ISSUE THREAD

**Issue by dubwalla** [WFP-VAM/prism-frontend#190]
There seems to be an issue when an analysis or an alert is created and the hazard layer is on WFP's GeoServer (in this case, ADAM tropical storm data). The same request using a hazard layer on WFP's Open Data Cube responds without an issue

Console error:
_Access to fetch at 'https://prism-api.ovio.org/stats' from origin 'http://wfp-prism-mmr-test-v1.s3-website-ap-southeast-1.amazonaws.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled._

Request payload: 
_{"geotiff_url":"https://geonode.wfp.org/geoserver?service=WCS&request=GetCoverage&version=1.0.0&coverage=wld_gdacs_tc_events_buffers&crs=EPSG%3A4326&bbox=92.2%2C9.7%2C101.2%2C28.5&width=1098&height=2304&format=GeoTIFF&time=2021-04-24","zones_url":"http://wfp-prism-mmr-test-v1.s3-website-ap-southeast-1.amazonaws.com./data/myanmar/admin_boundaries.json","group_by":"TS"}_

**Comment by dubwalla** [comment]
@ericboucher and @JorgeMartinezG  - can you have a look at this? we've got additional work to do on the expected behavior for storm analysis and alerts, but in the meantime, the CORS error needs to be addressed

**Comment by JorgeMartinezG** [comment]
@dubwalla somehow it is an API error which is wrapped into a CORS error. You can check the status code server response, by disabling cors for your browser. Using a terminal, run:

```sh
open -n -a /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --args --user-data-dir="/tmp/chrome_dev_test" --disable-web-scurity
```
However if you want to check the REAL error you would need to modify the ANALYSIS_API_URL and DEV_ADMIN_BOUNDARIES_URL to point to your local instance: https://github.com/WFP-VAM/prism-frontend/blob/master/src/context/analysisResultStateSlice.ts#L30

Related to the error itself, the payload shows you are executing a WCS request to the wind buffers layer, which is a vector one. Geoserver does not generate geotiffs from vector data using requests.

**Comment by dubwalla** [comment]
Thanks Jorge. Indeed, this seemed to be an issue related to the data type
