### ISSUE TITLE
Set geometry type for vector layers

### ISSUE THREAD

**Issue by JorgeMartinezG** [WFP-VAM/prism-frontend#191]
In order to validate that a layer is able to perform population exposure analysis, a geometry type  needs to be included within its configuration options. Also, there needs to be a check in order to remove vector layers for common analysis.

**Comment by wadhwamatic** [comment]
I believe you're working on something similar here @DanielJDufour ?

**Comment by wadhwamatic** [comment]
closed via https://github.com/WFP-VAM/prism-frontend/pull/192
