### ISSUE TITLE
Link within an alert from localhost points to prism-mongolia.org

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-frontend#207]
I'm not sure if this will be an issue after deployed, but when generating an alert from localhost, the prism_url is set to prism-mongolia.org. Can we ensure that this will correctly get the domain from which the request was generated?

**Comment by wadhwamatic** [comment]
Can you look into this as we revisit alerts @ericboucher ?

**Comment by wadhwamatic** [comment]
@ericboucher - can you look into this?

**Comment by ericboucher** [comment]
This is the function we are using to save the prism_url

https://github.com/WFP-VAM/prism-frontend/blob/master/src/utils/analysis-utils.ts#L194

It defaults to prism-mongolia for localhost only.
