### ISSUE TITLE
Stats API gives a 500 error on prism.mmr.wfp.org

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-frontend#243]
When running an analysis or exposure analysis, the API gives a 500 error. 
![image](https://user-images.githubusercontent.com/3343536/130994973-3d431f24-5087-4d5d-b69c-d1c249e8aba9.png)

**Comment by wadhwamatic** [comment]
Thanks Jorge. I pushed PR 245 to prism.mmr.wfp.org but get another error now (see below). Can you have a look?

Regarding the central folder for admin boundaries, sure - let's do that. Another issue forthcoming..

analysis-utils.ts:214 POST https://prism-api.ovio.org/stats 500
(anonymous) @ analysis-utils.ts:214
u @ runtime.js:45
(anonymous) @ runtime.js:274
forEach.t.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
jt @ main.54dc69dc.chunk.js:1
Et @ analysis-utils.ts:209
(anonymous) @ analysisResultStateSlice.ts:233
u @ runtime.js:45
(anonymous) @ runtime.js:274
forEach.t.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ analysisResultStateSlice.ts:207
(anonymous) @ createAsyncThunk.ts:415
n.condition.n.condition.getState @ helpers.js:565
(anonymous) @ 2.8d31b8fc.chunk.js:2
Et.Object.assign.pending @ createAsyncThunk.ts:396
(anonymous) @ index.js:8
(anonymous) @ exposedPopulationAnalysis.tsx:83
u @ runtime.js:45
(anonymous) @ runtime.js:274
forEach.t.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ exposedPopulationAnalysis.tsx:66
s @ react-dom.production.min.js:14
p @ react-dom.production.min.js:14
(anonymous) @ react-dom.production.min.js:14
v @ react-dom.production.min.js:15
ae @ react-dom.production.min.js:52
ie @ react-dom.production.min.js:51
se @ react-dom.production.min.js:52
pe @ react-dom.production.min.js:56
it @ react-dom.production.min.js:287
ut @ react-dom.production.min.js:23
Je @ react-dom.production.min.js:70
$e @ react-dom.production.min.js:69
e.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
nt @ react-dom.production.min.js:287
Ze @ react-dom.production.min.js:68
Show 19 more frames

**Comment by JorgeMartinezG** [comment]
@wadhwamatic the error is because the url to download the admin boundaries from the backend needs username / password. So the api throws an error.

I can replicate it directly in python by executing a request directly to the url:

```python
In [4]: requests.get("https://prism.mmr.wfp.org/data/myanmar/admin_boundaries.json").content
Out[4]: b'Unauthorized'
```

If i include the credentials, request works fine:

```python
In [7]: requests.get("https://prism.mmr.wfp.org/data/myanmar/admin_boundaries.json", auth=("wfp-mmr", "changeme"))
Out[7]: <Response [200]>
```

A quick solution would be to force using the s3 buckets url, no matter which environment we are using. cc @ericboucher
