### ISSUE TITLE
OWS layer config change

### ISSUE THREAD

**Issue by valpesendorfer** [WFP-VAM/prism-frontend#250]
Due to operational requirements, compound products such as rainfall aggregations and anomalies, need to be split out into standalone products within ODC.

The [respective PR](https://github.com/WFP-VAM/wfp-ram-odc/pull/10) will introduce the following changes that (could)  concern PRISM:

- changes in the hierarchical structure of the published layers
- new resource management to conform with new `datacube-ows` release (this will need testing and refinement; feedback will be much appreciated)
- **move layers that had styles controlling aggregation length / aggregation parameters into separate published layers**

The last point is the breaking one as the layers used by PRISM at the moment won't be available any more. This is how it breaks down:

`rnh_dekad`  will split into the layers:

- `r1h_dekad`
- `r2h_dekad`
- `r3h_dekad`
- ...
- `ryh_dekad`

with the style controlling the visualization as it does for `rfh_dekad`.

`rnq_dekad`  will split into the layers:

- `rfq_dekad`
- `r1q_dekad`
- `r2q_dekad`
- `r3q_dekad`
- ...
- `ryq_dekad`

with only one default style.

`rnq_blended_dekad` & `rnq_blended_dekad` will split the same way as the corresponding layers above.

`xln_dekad`  will split into the layers:

- `xlh_dekad`
- `xli_dekad`
- `xle_dekad`

with only one default style.

`xnn_dekad`  will split into the layers:

- `xnh_dekad`
- `xni_dekad`
- `xne_dekad`

with only one default style.

This will increase the number of published layers quite a bit - please let me know if that could have a negative impact for PRISM.

@wadhwamatic could you give an estimate how fast we can make this transition?

**Comment by wadhwamatic** [comment]
Thanks @valpesendorfer. The change on the PRISM side is fairly trivial, no more than 30 mins per deployment to configure and test. We can setup some time to coordinate implementing this on both sides.

**Comment by wadhwamatic** [comment]
I just noticed that the blended precip anomaly product is missing in this update

**Comment by valpesendorfer** [comment]
@wadhwamatic the blended anomaly products have been added - please note they are also split into separate layers now

**Comment by wadhwamatic** [comment]
> @wadhwamatic the blended anomaly products have been added - please note they are also split into separate layers now

Thanks, working for Mozambique now. I'll publish that change for review

**Comment by wadhwamatic** [comment]
Addressed via https://github.com/WFP-VAM/prism-frontend/pull/256
