### ISSUE TITLE
Hydrafloods layer config change

### ISSUE THREAD

**Issue by valpesendorfer** [WFP-VAM/prism-frontend#264]
@wadhwamatic @JorgeMartinezG  as discussed, the hydrafloods layers are now split between the two different countries.

e.g.:

`hfs1_sfw_mask` becomes

--> `hfs1_sfw_mask_khm` 
--> `hfs1_sfw_mask_mmr` 

and so on ...

**Comment by wadhwamatic** [comment]
thanks, myanmar addressed through https://github.com/WFP-VAM/prism-frontend/pull/266
cambodia through https://github.com/WFP-VAM/prism-frontend/pull/261
