### ISSUE TITLE
Error handling for layers

### ISSUE THREAD

**Issue by ericboucher** [WFP-VAM/prism-frontend#27]
Handle errors when fetching data.

In particular, have the ability to parse time mismatch "Time dimension value '2020-02-10' not valid for this layer".

And server errors (eg. server offline)

**Comment by ericboucher** [comment]
Linked to #7

**Comment by bencpeters** [comment]
Redux state now has an errors array in MapState (and an error string for table state and server dates).

We should probably just add a snackbar to display any errors.

This could potentially be implemented using a Redux middleware too.

**Comment by SimplyBallistic** [comment]
@laveesh and I are looking into implementing one of the two react notification APIs

1. https://teodosii.github.io/react-notifications-component/
2. https://toasted-notes.netlify.app/

Creating the notification will be pretty easy - just a function call. 

We could do this two ways:
1. Make a redux middleware and check every action that passes through.
    - If we see an action that we know counts as an error (e.g mapState/loadLayerData/rejected) we can read the payload and create the notification there.
2. Edit the reducers themselves to create a notification.
    - By editing every reducer that counts as storing an error (e.g in serverSlice) we can just create the notification there. 

Which do you think is better for the long run?

**Comment by SimplyBallistic** [comment]
Update: After some discussion with @laveesh, we've decided to use Material UI's [built in Snackbar](https://material-ui.com/components/snackbars/).

We also will be taking approach 1 to make things more stable in the long run (and as @bencpeters suggested). 

Look out for a PR!
