### ISSUE TITLE
Consider alternative to mapbox

### ISSUE THREAD

**Issue by ericboucher** [WFP-VAM/prism-frontend#271]
Now that Mapbox is not truly open-source anymore, we would like to consider alternatives.

Maplibre, a fork of mapbox-gl, seems to have emerged as a strong candidate with a healthy active community. Let's look into it a bit deeper and consider a switch to https://github.com/maplibre/maplibre-gl-js.

**Comment by DanielJDufour** [comment]
fwiw, I got maplibre running locally.  I can make a PR within the next few days after I clean up my code.
