### ISSUE TITLE
Look into facilitating a distinct admin boundary file for each admin level layer

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-frontend#277]
In the case of our regional deployment in West & Central Africa (RBD), we're working with admin level layers that could have a unique admin boundary file. For example, an admin level layer file for May 2020 may have a different definition of admin boundaries than an admin level layer file for May 2021. 

We'll need to allow for a configuration option for admin level layers that specifies an admin boundary file as well. We'll also need to consider the downstream implications of this change such as the inputs for spatial analysis

cc: @olanderb

**Comment by erwagasore** [comment]
This issue is linked to solve the grouping of similar layers https://github.com/WFP-VAM/prism-frontend/issues/122

**Comment by wadhwamatic** [comment]
Some additional input:
1. Add an attribute in the admin_level layer which is optional for a unique boundary file. We can call simply call it 'boundary'
2. We can use the id of the boundary file which has been setup in layers.json
3. When the admin_level layer is selected, it should unload the previous boundary file(s) and then display the unique boundary file
4. When the admin_level layer is deselected, it should unload the unique boundary file and then reload the default boundary display
