### ISSUE TITLE
Explore UI options to choose admin level / area of interest

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-frontend#278]
As we start to deploy regional versions of PRISM with multiple countries, we need to think about how to best allow users to drill down from regional to country to sub-national views. See an example from [RBD's R Shiny dashboard](https://bolander.shinyapps.io/shiny_new/) for Cadre Harmonise data as an example:

<img width="1425" alt="Screen Shot 2021-10-20 at 11 37 47" src="https://user-images.githubusercontent.com/3343536/138151980-cb3f47ed-179c-4ad2-9f98-6d1e69369191.png">

In addition to the different view / zoom, we'll also need to think about how different layers could become available based up on the view. For example, some layers may be applicable regionally, but once at national level, other layers may become relevant for that country only. 

cc: @olanderb

**Comment by erwagasore** [comment]
https://www.figma.com/proto/1DQG4w9VGDcNNt6BSf7g1s/RDB?page-id=0%3A1&node-id=1%3A2&viewport=241%2C48%2C0.06&scaling=min-zoom&starting-point-node-id=1%3A2
