### ISSUE TITLE
Improve config definition for servers and layers

### ISSUE THREAD

**Issue by ericboucher** [WFP-VAM/prism-frontend#29]
We need to centralize information on servers and have a "parameter" approach for layers / types.

**Comment by SimplyBallistic** [comment]
What progress was made in #25? Was it solved?

If not, is it possible to elaborate on what needs to be achieved? Specifically on 

>  centralize information on servers

and 

> "parameter" approach for layers / types

**Comment by ericboucher** [comment]
We are currently using a `base_url` in layers.json for raster servers, combines with a wcs_config if one is available.

Eg:  "base_url": "https://mongolia.sibelius-datacube.org:5000",

Instead, we should allow the creation of "severs" in the prism.json file, and use the server_id in the layers.json instead. This would make it easier to change what server we are pointing too.

The server config for rasters could also have a `wms_path` and an optional `wcs_path`, indicating that WCS capabilities are available.


I think we have started the "parameter" approach, although a lot of the names and functionalities are quite specific for Mongolia.

I was envisioning that we would have broader types to cover more "standard" options.

Eg:
- points_geojson
- vector_geojson
- raster
- impact

**Comment by dubwalla** [comment]
Yes, this is a bit of a priority as the naming convention at present is overly specific to Mongolia. I had on my to do list to create an issue on this specifically.

The examples above (points_geojson, vector_geojson, and raster) are good. Impact is based on a current use case, but in practice the output of an analysis could be 'impact', 'spatial stats', and more. Future analysis outputs could include points and rasters too. Do we need to create separate types for each?

**Comment by dubwalla** [comment]
I also wanted to note that WMS layers are not only rasters. A WMS could also return point or vector data

**Comment by ericboucher** [comment]
For now the consensus is to rename layers to the following:

NSO -> admin_level_data
Groundstation -> point_data

**Comment by wadhwamatic** [comment]
Addressed most of what was required here. New issues will be created to address gaps based on more current structure
