### ISSUE TITLE
Look into masking raster data outside of boundary file

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-frontend#291]
Does Mapbox allow for a vector file to mask a raster? Can we only show raster data (i.e. ODC data from WMS) that lies within the admin boundary file?

**Comment by ericboucher** [comment]
@wadhwamatic can you give a specific example to replicate here? Potentially, we could limit the data we are requesting from the ODC to the polygon, or rectangle closest to our country of interest.

**Comment by wadhwamatic** [comment]
closing this as we made some progress (though not complete) under https://github.com/WFP-VAM/prism-frontend/issues/170
