### ISSUE TITLE
Inconsistent use of admin levels and sequence based on admin_level_names

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-frontend#334]
The admin_level_names attribute's sequence of values is not consistently used. In the exposure analysis, it seems the first value is considered the lowest level boundary (i.e. admin 2 in the case of Mozambique, and admin 3 in the case of Myanmar). 

In PR https://github.com/WFP-VAM/prism-frontend/pull/329, the sequence is interpreted the opposite way.

As mentioned before, we should consider an explicit definition of admin levels so we can avoid this. For example, if an admin boundary layer has multiple levels, we could do something like the configuration below. Open to suggestions though.

        "admin_levels": {
            "state": {
                "level": 1,
                "admin_code": "ST_CODE",
                "admin_level_name": "ST",
                "admin_level_local_name": "ST_MMR"
            },
            "district": {
                "level": 2,
                "admin_code": "DT_CODE",
                "admin_level_name": "DT",
                "admin_level_local_name": "DT_MMR"
            },
            "township": {
                "level": 3,
                "admin_code": "TS_CODE",
                "admin_level_name": "TS",
                "admin_level_local_name": "TS_MMR"
            }

**Comment by wadhwamatic** [comment]
@Ry-DS - can you also have a look at this? I'm not sure how we've implemented the order in PR https://github.com/WFP-VAM/prism-frontend/pull/308 

cc @ericboucher

**Comment by Ry-DS** [comment]
I can confirm this is a little broken for myanmar which I had to fix by flipping the access levels in 3bd86b7934da81e3a23f662c00b382619b2da4e4. We can fix this temporarily by making sure all layer configs order their `admin_level_names` consistently, and explore a more complete solution here.

**Comment by ericboucher** [comment]
I think using the order of `admin_level_names` should be fine, as long as we agree on the order.

**Comment by wadhwamatic** [comment]
Ok @ericboucher - agreed to not add an attribute for this. But there is a problem with consistency. In 'run analysis', we seem to use the last admin layer specified for the group by function. In 'exposure analysis', we use the first admin level specified. 

For example, a 'run analysis' in Myanmar uses group by "TS" while an exposure analysis in Myanmar uses group by "ST". See screenshots below. The other factor is that we're adding the ability specify admin boundaries associated with a 'baseline layer'.  We need to enforce that in the group by parameter when we do a 'run analysis'. See issue https://github.com/WFP-VAM/prism-frontend/issues/341 

Run analysis is grouped by township (admin 3):
<img width="445" alt="Screen Shot 2021-12-17 at 12 05 20" src="https://user-images.githubusercontent.com/3343536/146602116-c0045518-8de4-4815-a7ec-25f1c7a75fb0.png">

Exposure analysis is grouped by state (admin 1)
<img width="626" alt="Screen Shot 2021-12-17 at 12 07 09" src="https://user-images.githubusercontent.com/3343536/146602124-df10a4c2-6891-4c79-8513-57d0b987d27f.png">

Assigning this to @erwagasore as it relates to issue 341, also on his plate. Eugene - the way forward will be to use the 'baseline' layer's admin level to group by when running an analysis; and for exposure analysis, use the lowest level available from the 'primary' boundary file
