### ISSUE TITLE
Maintain map position when loading a new layer

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-frontend#345]
Resetting the map position whenever we load a new layer is frustrating. A user may have zoomed / panned to a specific area of interest but then loses that positioning by activating a new layer. We need to change the behavior so that the map position is not reset whenever we load a new layer.

**Comment by reed1** [comment]
Hi @wadhwamatic, there is a small patch here to prevent map re-centering. 4be2b7fa42b1084e10fe78f23a5ad7ece91d8767

You can test it on https://prism.wfp.or.id/ . If it's good enough I can make PR for that

**Comment by wadhwamatic** [comment]
That's great, thanks @reed1. This just came up again today. Yes, please go ahead with a PR and I'll test it in other deployments as well.
