### ISSUE TITLE
Integrate EWS-1294 data into PRISM Cambodia

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-frontend#351]
EWS-1294 (http://ews1294.com) is a flood early warning system in Cambodia which monitors river levels using sensors across the country. Each sensors has a fixed location with multiple new readings every hour. 

There are two components to the API: locations, and data points. We need to be able to configure the EWS-1294 data as a 'point' layer which dynamically retrieves data through the API endpoint.

The descriptions below are from the EWS-1294 technical lead. 

**Locations API**
http://sms.ews1294.info/api/v1/location.geojson?type=river
In the objects, you can find the names (both English and Khmer), locations, trigger levels, status of each location we have (or plan to have) sensors installed (note that we have 2 status fields – `status` which is dynamically updated between active and inactive depending on whether the sensor is sending data or not, and ´status1´ which is our internally expected status, and can have the values of Test, Planned or Operational – For PRISM, I suggest you only show the ones marked as Operational). We expect the list of locations to reach about 50 before next rainy season.
 
**Datapoint API**
http://sms.ews1294.info/api/v1/sensors/sensor_event?location=22&start=2019-07-01&end=2019-07-19
Using the location id (from the location API), as well as a start and end date (in any format understood by PHP), you can get the water heights reported by the sensors in that period. Without start and end provided, the API will default to return only the last 6 hours. I would advise against loading more than one month at a time, as this might hit the server harder than needed 😊

**Comment by wadhwamatic** [comment]
@erwagasore - as discussed today, let's approach this as two separate queries: 1) get data from all sensors on a single day, and 2) if a user clicks on a sensor location, query the past seven days of available data for that location (time interval TBC). 

For the first query, we'll need to summarize data. Let's start by computing the mean, median, min and max value for each sensor on a specific day. Once we have this task complete in a PR, we can start visiting the second query.

**Comment by erwagasore** [comment]
@wadhwamatic I am experiencing issue with `ews-1294` API when called twice or three times in a short time it is crashing  with error e.g. 
```
error: Internal server error: 429 Client Error: Too Many Requests for url: http://sms.ews1294.info/api/v1/sensors/sensor_event?external_id=TEPv4.0-033&start=2022-01-28&end=2022-01-29
```
As a context since I am looping on each location using `http://sms.ews1294.info/api/v1/location.geojson?type=river` and get data for that location by calling `http://sms.ews1294.info/api/v1/sensors/sensor_event?external_id={id-here}&start=2019-07-01&end=2019-07-19` I am calling the `datapoint api` api `21` times for just as single day. If we were to use these endpoints on different days  from `May 2021` we would have many crashes. Something to engage with Cambodia team

**Comment by wadhwamatic** [comment]
This has been addressed via https://github.com/WFP-VAM/prism-frontend/pull/461
