### ISSUE TITLE
Support Kobo forms that map to admin_level_data rather than point data

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-frontend#352]
In some instances (including Cambodia), Kobo form data will not include a lat/long but instead will capture data at the admin level (i.e. district or commune). We'll need to have a similar approach for pulling data from the Kobo API, but do render the result as an admin level layer rather than point layer. I'll create a form for testing soon. See 'PRISM-KHM-Disaster-Report-v2-no-lat-long' in our shared Kobo user in the meantime. It has province and district fields, but returns text rather than the admin code.

 
https://docs.google.com/document/d/1O9VvyfhY7FEprpVWN6YYGYleF92615QodWMs2o1qLxw/edit

**Comment by wadhwamatic** [comment]
@ericboucher and @tdlinh2712 - I added a branch 'khm_kobo_03_2022' to test and create forms that will need to use admin codes instead of a lat/long. See issue https://github.com/WFP-VAM/prism-frontend/issues/407 for a problem related to groups in forms. 

In layers.json, change "test-form-admin-codes" to "test-form-admin-codes-no-groups". That will give you a working form with admin codes as part of the submitted data. The data fields of interest are called Province, District and Commune. For now, this form also has a lat/long as our current functionality doesn't work without it. Hoping this gives you enough to start implementing this change.

One thing of note - I think we should consider two ways to visualize data that is captured at admin level: 1) shade the full admin polygon or 2) place a point at the center of the polygon. It would be great if we could do either and allow it to be a config option.

**Comment by ericboucher** [comment]
Does the commune match data we have in our admin boundary layer?

**Comment by wadhwamatic** [comment]
> Does the commune match data we have in our admin boundary layer?

@ericboucher - Almost. The discrepancy I see is that the Kobo forms use leading 0s for provinces 0-9 and that carries over to district and commune codes. 

For example, in the Kobo form, province '7' is labeled '07', a district within it is '0702', and a commune within it is '070204'.
In the boundary file, that same commune is '70204'. 

I'm not sure if removing the leading 0 in the Kobo form will break something. We can try it out.
