### ISSUE TITLE
Values displayed in analysis results in tooltip are rounded

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-frontend#368]
The values we show in the tooltip after running an analysis are rounded to whole numbers. Can we have this somehow configurable based on the hazard layer? It also doesn't match the value displayed in the table. See screenshot below from Sri Lanka dev branch, SPI hazard layer.
<img width="1419" alt="Screen Shot 2022-01-26 at 19 28 20" src="https://user-images.githubusercontent.com/3343536/151286926-cb7deb20-22f0-4c5d-b7b0-2aad71e08a51.png">

**Comment by ericboucher** [comment]
To start, I suggest that we add a 2 digit precision everywhere but remove insignificant trailing zeros.

**Comment by Ry-DS** [comment]
Is the sri lanka branch up to date? Looked for examples on master with Linh but can't find any. First steps might be to update the sri lanka branch and see if the issue persists.

**Comment by Ry-DS** [comment]
Also, reckon it's a good plan to move Sri lanka to master like all of the other countries? (make it have its own folder)

**Comment by ericboucher** [comment]
@wadhwamatic can you add more details about the mismatch? And steps to reproduce? Thanks :)

**Comment by wadhwamatic** [comment]
> Also, reckon it's a good plan to move Sri lanka to master like all of the other countries? (make it have its own folder)

Hi Ryan. Sri Lanka is up to date on Master: https://github.com/WFP-VAM/prism-frontend/tree/master/src/config/srilanka

**Comment by wadhwamatic** [comment]
> @wadhwamatic can you add more details about the mismatch? And steps to reproduce? Thanks :)

@ericboucher - see the original screenshot and description. It's all there. =)
run analysis > SPI + poverty headcount. Table view shows the expected result but the tooltip result is rounded to a whole number

**Comment by tdlinh2712** [comment]
Hi @wadhwamatic, can you explain further what you meant by making it configurable based on the hazard layer? does it mean to make the tooltip value match the table value?

**Comment by wadhwamatic** [comment]
> Hi @wadhwamatic, can you explain further what you meant by making it configurable based on the hazard layer? does it mean to make the tooltip value match the table value?

Hi @tdlinh2712. Thanks for working on this. I meant that the rounding rule could be part of the layer configuration, i.e. with a new layer attribute called 'precision' or something similar to specify how many decimal points to round to. Otherwise I think 2 or 3 digits after the decimal point would be ok
