### ISSUE TITLE
Matching on a numeric admin code fails

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-frontend#384]
If the admin code in a boundary file is an integer, the corresponding admin_level_data match fails. There will be cases where the admin code is not a string, which we should support. Hoping we can address this soon as I believe it's a minor fix and we have more deployments coming in quickly.

**Comment by ericboucher** [comment]
Could you add steps to repdouce @wadhwamatic ? Thanks :)

**Comment by wadhwamatic** [comment]
Steps to reproduce:
1. Use this branch: moz-updates-2022-02
2. Note the 'admin_boundaries' file has been updated (../data/mozambique/moz_admin_boundaries_WFP_CO_2022_02.json) 
3. The new admin boundary file includes a numeric id field 'adm2_id'
4. Change the 'admin_code' config for the 'admin_boundaries' layer to 'adm2_id'
5. Also change the 'admin_code' config for the layer 'ipc_pop_ph3_current' to 'adm2_id'
6. Activate the layer  'ipc_pop_ph3_current' (label is "Number of people currently in IPC Phase 3+")

You'll then see an error in the interface, and in the console:
TypeError: adminBoundaryCode.startsWith is not a function
    at admin_level_data.ts:83:1
    at Array.find (<anonymous>)
    at admin_level_data.ts:83:1
    at Array.map (<anonymous>)
    at admin_level_data.ts:76:1
    at async layer-data.ts:87:1

**Comment by wadhwamatic** [comment]
Addressed with https://github.com/WFP-VAM/prism-frontend/pull/396
