### ISSUE TITLE
Mongolia admin_leve_data data values are strings and not treated as numeric when sorting

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-frontend#398]
The sort function highlights a problem with data in Mongolia which includes string values instead of numeric. See screenshot from Mongolia:

<img width="1411" alt="Screen Shot 2022-03-07 at 11 49 45" src="https://user-images.githubusercontent.com/3343536/157107455-56c92c0e-3bbb-4a92-8f54-13044439085d.png">

The values are wrapped in strings as part of the API we used to get data from Mongolia. Can we implement a process to convert these to numeric? 

Steps to reproduce:
1. On master, REACT_APP_COUNTRY=mongolia
2. Run analysis with hazard layer 'Pasture anomaly' and baseline layer 'total population. Leave thresholds blank. Choose any date
3. Sort results by total population

**Comment by ericboucher** [comment]
Should be fixed in #396
