### ISSUE TITLE
Indonesia boundary file not found in S3

### ISSUE THREAD

**Issue by reed1** [WFP-VAM/prism-frontend#401]
The URL is:

https://prism-admin-boundaries.s3.us-east-2.amazonaws.com/idn_admin_boundaries.json

we're using self-hosted URL for now:

https://prism.wfp.or.id/data/indonesia/admin_idn.json

Just in case it is needed for other services, please check, thank you

**Comment by wadhwamatic** [comment]
@reed1 - I uploaded the boundary file that was on prism.wfp.or.id to S3:
https://prism-admin-boundaries.s3.us-east-2.amazonaws.com/admin_idn.json
