### ISSUE TITLE
The CSV file generated when downloading results doesn't have headers for each admin level

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-frontend#402]
After running an analysis, the table view now shows all admin levels, separated by commas. But when we generate a CSV file to download, the headers don't exist for each admin level so we have mismatched columns. See screenshots below. Suggest to add column headers 'admin1', 'admin2', etc.

Steps to replicate:
1. On master branch, REACT_APP_COUNTRY=cambodia yarn start
2. Run analysis: 10-day rainfall + IDPoor, no thresholds, any date
3. At the bottom of the table results, click 'Download' and open the CSV file

<img width="755" alt="Screen Shot 2022-03-11 at 08 32 04" src="https://user-images.githubusercontent.com/3343536/157908644-3237107f-366a-4ead-8531-911bef711f06.png">

<img width="417" alt="Screen Shot 2022-03-11 at 08 32 52" src="https://user-images.githubusercontent.com/3343536/157908680-e56385a9-1fad-4189-8d8f-50fe5683b59d.png">

**Comment by wadhwamatic** [comment]
Can you have a look @tdlinh2712 ?

FYI @ericboucher ^^

**Comment by ericboucher** [comment]
The CSV download should probably be a raw dump of the data, so we should probably fix the parsing and make sure the admin names stay in one column. If we want to have multiple columns for admin names, we should probably do that for the table itself directly.

**Comment by ericboucher** [comment]
@wadhwamatic follow-up question, should the data be downloaded `translated`? related to #382
