### ISSUE TITLE
Add direct link to layer and date that triggered an alert

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-frontend#408]
When an alert is triggered, the message that is produced should be updated to reflect 1) the location of the application that requested the alert job and 2) a direct link to the application with the date and layer that corresponds to the alert.

For example, if the alert job was created on https://prism-demo-moz.surge.sh/ for the layer rfh_dekad and the threshold was exceeded for an observation on 11-March-2022, the link should go to https://prism-demo-moz.surge.sh/?hazardLayerId=rainfall_dekad&date=2022-03-11

Here's a screenshot of the current message for reference:
 <img width="669" alt="Screen Shot 2022-03-17 at 11 30 00" src="https://user-images.githubusercontent.com/3343536/158871741-1db844b7-6c3e-48d8-bae6-66fd9bef9a60.png">

**Comment by ericboucher** [comment]
Are you sure the alert was created from there and not locally? The prismUrl is passed in but it defaults as prism-mongolia if it is not present, eg. when running the app locally.

**Comment by wadhwamatic** [comment]
@ericboucher - That is possible. I'll test again on a surge deployment.

**Comment by ericboucher** [comment]
@wadhwamatic let me know when you do and I can check directly in the DB that if it got set properly

**Comment by wadhwamatic** [comment]
I received an alert which was created from a surge deployment, and can confirm that it gave the right domain. But we still need to update the link to use the layer and date that triggered the alert.

<img width="457" alt="Screen Shot 2022-03-28 at 11 21 32" src="https://user-images.githubusercontent.com/3343536/160497777-09d28bad-6d2e-4fa5-91f6-aeb0723efd1e.png">
