### ISSUE TITLE
Vertical scrollbars occasionally appear while the top navigation becomes inaccessible

### ISSUE THREAD

**Issue by hav142** [WFP-VAM/prism-frontend#411]
There is a small issue with the PRISM layout where scrollbars appear on the right and bottom sides. 

![image](https://user-images.githubusercontent.com/25983260/158934703-40a70c93-a6c1-4eda-8da5-f45e0d336512.png)

It should be fixed by moving some attributes in the app.css as I noticed that the HTML structure for the map container seems to have changed a bit from the previous version.

![image](https://user-images.githubusercontent.com/25983260/158946852-3674d489-bd0e-44b6-8208-cbba8e5ac8f0.png)

@wadhwamatic let me know if this fix is OK then I will submit a PR.

**Comment by wadhwamatic** [comment]
@hafidz142 - please go ahead and implement your suggested change through a PR and we can then review it
