### ISSUE TITLE
Unable to add translations to Analyser and AlertForm

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-frontend#481]
There is text in the Analyzer component that I'm unable to add translations for.

The text reads: 
"Below threshold is larger than above threshold!"

I added translations for that text in translations.json, but there's no change seen.

<img width="409" alt="Screen Shot 2022-05-26 at 13 14 23" src="https://user-images.githubusercontent.com/3343536/170572486-6990df70-3fa2-4f43-8b93-2a473924d205.png">

It also seems that none of the text in the Alerts module is marked for translation (besides layer names):

<img width="278" alt="Screen Shot 2022-05-26 at 13 17 14" src="https://user-images.githubusercontent.com/3343536/170573087-e4edb24f-827d-4110-a436-a092f6cebe79.png">

**Comment by tdlinh2712** [comment]
@wadhwamatic can you provide some instruction on how to reproduce the "Create Alert" modal please?
