### ISSUE TITLE
Facilitate population exposure analysis for floods

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-frontend#509]
PRISM currently allows for exposure analysis of tropical storms and earthquakes, which are vector / polygon data, while the population data is a raster dataset from WorldPop, served through WFP's Open Data Cube deployment. This works well for estimating the number of people exposed to various wind buffers for storms, and shake intensity for earthquakes. But we also need to be able to calculate the number of people exposed to floods, which is based on a raster dataset.

Let's start with Myanmar as our first use case of this, with Cambodia to follow. We have WorldPop data available for Myanmar through ODC (layer name: wp_pop_cicunadj), and flood estimates as well (layer name: hfs1_sfw_mask_mmr). Flood data is at 10m resolution, while population data is at 100m resolution, so we have to either resample one of the datasets to match the other (i.e. upsample flood data, or downsample population data); or create a vector of the flood area and then use the same process we use for population exposure analysis of storms and earthquakes.

Please share inputs here before we start developing a solution.

**Comment by DanielJDufour** [comment]
Hi, @wadhwamatic .  Looks like a very interesting problem.  I have the following questions in mind:
- What does the population data (wp_pop_cicunadj) look like?  Do pixel values (i.e. grid cells) represent the total number of people per pixel or a population density/ratio (like people per 1 sqkm) or something else?
- For the purposes of this calculation, can we safely assume even distribution of population a wp_pop_cicunadj grid cell?  Therefore, if we divide the grid in 4 pieces, does each piece represent 1/4 the value of the grid cell?  (If it's density metric, then downsampling/dividing doesn't actually change the cell value)
- What does the flood estimates (hfs1_sfw_mask_mmr) look like?  Is binary (not flooded / flooded), water level, or something else?  For the purpose of these calculations, should our result be binary (flooded or not) or include the severity of flooding?
- What projections are the different datasets in (wp_pop_cicunadj and hfs1_sfw_mask_mmr)?  I'm assuming/hoping EPSG:4326 in which case the calculations are rather easy and don't require any warping/reprojection.
- Are the calculations results meant to be visualized on a map, table or both? I assume both, but want to double check.

fwiw, I think it's definitely worth exploring whether we can do these calculations on the front-end without a server.  It'll depend on the answers to the questions above though.  If both datasets are in EPSG:4326, it greatly simplifies the Math and would be relatively straightforward.  Various algorithmic approaches could be taken, sampling evenly spaced points at a high resolution (small distance between points), vector-based intersections (reuse zonal?), iterating over flood pixels and matching their locations to corresponding population pixels.

Happy to discuss and think more on it, but wanted to get some thoughts out early.

**Comment by wadhwamatic** [comment]
Hey @DanielJDufour - glad to hear you're thinking about this one. See my answers below:

> What does the population data (wp_pop_cicunadj) look like? Do pixel values (i.e. grid cells) represent the total number of people per pixel or a population density/ratio (like people per 1 sqkm) or something else?

Each pixel value represents the estimated total number of people per grid-cell. You can find more details here (Myanmar as an example): https://hub.worldpop.org/geodata/summary?id=49759 

> For the purposes of this calculation, can we safely assume even distribution of population a wp_pop_cicunadj grid cell? Therefore, if we divide the grid in 4 pieces, does each piece represent 1/4 the value of the grid cell? (If it's density metric, then downsampling/dividing doesn't actually change the cell value)

Yeah, we would have to make an assumption about an even distribution with the cell. It's not ideal, but I don't see an alternative based on the data we have

> What does the flood estimates (hfs1_sfw_mask_mmr) look like? Is binary (not flooded / flooded), water level, or something else? For the purpose of these calculations, should our result be binary (flooded or not) or include the severity of flooding?

Yes, this is a binary variable with values of flooded vs non-flooded. In the future we may have a flood severity score but for now it's just binary. 

> What projections are the different datasets in (wp_pop_cicunadj and hfs1_sfw_mask_mmr)? I'm assuming/hoping EPSG:4326 in which case the calculations are rather easy and don't require any warping/reprojection.

Yes, both are available as EPSG:4326. I just checked (https://odc.ovio.org/wms?request=GetCapabilities) and saw both are also available as EPSG:3857. But I am 95% certain that our data cube WCS provides EPSG:4326 by default. @valpesendorfer - can you confirm that? 

> Are the calculations results meant to be visualized on a map, table or both? I assume both, but want to double check.

Both!

Great if we can do this on the front-end, though I could also see value in making this another capability of the API for use beyond PRISM deployments. Shoot over any other questions you have. We can hop on a call too, I'm in San Francisco for the next two weeks.

**Comment by valpesendorfer** [comment]
The original data is in EPSG:4326, but you can request it through WCS in all CRS' defined in the service.

**Comment by valpesendorfer** [comment]
Given the pop layers are single datasets and are fairly static, we could facilitate access outside of WCS if that would make it easier (would for the backend for sure)

**Comment by ericboucher** [comment]
@valpesendorfer it could be interesting to store the population layer with a resolution that matches the data we get for floods. As you can see in #546 we need to reproject and scale the data, which is quite costly.

**Comment by valpesendorfer** [comment]
Hm, yes a possibility ... but feels like a backwards approach, increases the uncompressed storage requirement by a factor of 10. Since I'm not familiar with #546, why do you need to reproject? Same CRS, could you not do a simple NN-resample?

Option B, finally integrate STAC and load only AOI with resample on the fly :rocket: :grimacing:
