### ISSUE TITLE
Add a timer to automatically remove warning messages on the front end

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-frontend#530]
The frontend currently displays warning messages which persist until a user closes them. We can also accumulate more than one message at a time. Let's instead remove the message after 10 seconds. The screenshot below shows two messages together which we'd want to avoid.  

<img src="https://user-images.githubusercontent.com/16843267/180460677-373d269d-58bb-49bf-a3c3-090accad25c2.png">

**Comment by PysarenkoDS-BWT** [comment]
Do we need to add some kind of indication that there is an auto-closing? Countdown  timer for example
