### ISSUE TITLE
Add WorldPop data for Cambodia to HDC

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-frontend#535]
@valpesendorfer - Please add WorldPop data for Cambodia to HDC. We'll need to use this next week for flood exposure calculation

https://hub.worldpop.org/geodata/summary?id=49950

cc: @ericboucher

**Comment by valpesendorfer** [comment]
added and available:

https://radiantearth.github.io/stac-browser/#/external/api.earthobservation.vam.wfp.org/stac/collections/wp_pop_cicunadj/items/wp_pop_cicunadj_khm_2020
