### ISSUE TITLE
Add date as an attribute of ground station (aka point) and nso (aka admin_level) data layers

### ISSUE THREAD

**Issue by dubwalla** [WFP-VAM/prism-frontend#96]
Each type of layer can have a date attribute associated with it but currently only WMS layers have this implemented. We need to be able to display the appropriate data based on a point in time. For example, for ground station data in Mongolia, a new reading is collected every 10 days but the current implementation can only show the latest available data. And in Indonesia, some of the baseline / vulnerability / nso layers may have different values based on the month and year. 

An MVP version of this could include the layer configuration to specify the date interval required and available dates with data. A more ideal solution would to have some service that determines the interval and available dates automatically but that would require something like WMS GetCapabilities on external sources that we may not have control over. @ericboucher - what do you think?

A solution for this in Mongolia for the ground station data needs prioritization. A solution for nso layers could come later, but it would be great if we can solve for both cases together.

**Comment by SimplyBallistic** [comment]
point data layers were given date support in #102 but there were certain trade-offs. Start-up times are lengthened since we cannot query just possible dates from the API. The API itself takes quite awhile to respond to such a request: 
![image](https://user-images.githubusercontent.com/25571542/91001222-7b40db00-e60e-11ea-83af-4a884e73beac.png)

**Comment by dubwalla** [comment]
Fixed for point data but not NSO data. NSO data is covered in https://github.com/WFP-VAM/prism-frontend/issues/126. Closing this issue
