### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by ericboucher** [WFP-VAM/prism-frontend#97]
We would like the app to be available in multiple languages.

We can use i18next and have a similar approach as https://github.com/mapswipe/website/pull/33

**Comment by ericboucher** [comment]
From @laurentS:

I've used i18next for both the app and the website, they have a couple of different but related libs that you can include in the project. Overall, it works well, and is sufficiently flexible for our needs (which are pretty simple). Marking up all strings for translation can be a bit heavy though, as you need to pass around a function or react component with a reference to the translated text everywhere. You can do this with a HOC in react, or something else, but overall, it's quite verbose, and other libs might be better at it. Plan on spending a fair bit of time on this, it's a simple task, but it's tedious and error prone.

I never managed to get the string collection part to work (the code which reads your source code and collects all the strings that need translating). For mapswipe, it's quite small, so we manage by hand, but on a big project, you definitely want this to work. I'm not sure why it's not working, I haven't touched this in ages, but the fact that I couldn't figure it out might be a (light) red flag.

Once you've marked all the text to translate, you need to actually translate it. I've only ever used transifex for this, because the osm ecosystem is mostly on it, so we chose to go where translators are to limit friction. It works, but the UI is not the best, and they've had some weird bugs in their github integration (which gives us a PR for every new completed/updated translation) which created hundreds of PRs on mapswipe for no good reason. Their support is a bit crap, but maybe better if you're paying, I don't know. On the plus side, it has worked for years. Having not tried anything else, I can't compare. Whatever you go with, make sure it works with the lib you use in your code, as there are dozens of file formats for translation management, and docs were overall not super impressive when I researched this. Probably because they're all trying to get you on their translation platform (which is where they make money), so they don't say much about compatibility.

Last step, you need to get the translations back into the code/app. transifex has a hook on github which automatically pulls the new main lang file (English usually) and makes it available to translators, and sends a PR when some translation is completed or validated. I guess other platforms have the same thing, probably better.

Basically, you'll have to work out what your workflow will be for translations, because the code bits you use might be dictated by compatibility.

with what we have, mapswipe (mostly the app, because we get more volunteer work on it) is available in 15-20 languages including japanese, nepali and farsi (written right to left), so I'd say most languages should be handled ok. The app's language can be swapped online with no refresh/reload.

Just don't underestimate the time need to mark all the text for translation, it takes a while. It also makes your release process that much longer, because each time you add/change a bit of text, you now need to sync N translations before you can release, unless you're ok with a fallback language in some parts of your app.


Final thought - Maybe check what ID uses (the osm editor), as it would have a wide choice of languages

**Comment by Ry-DS** [comment]
I'm not too experienced with localisation, but from what's here I definitely think i18next is the way to go coupled with react-i18next. Using automatic tooling to automatically find all strings and replace them with localisation would be perfect. While hoc is suggested here, I think a hook pattern should work better. I found this resource quite useful in suggesting ways to handle lazy loading, hooks etc: https://phrase.com/blog/posts/localizing-react-apps-with-i18next/

I also want to stress how we should use TS strongly here, possibly enums which will make it incredibly easy to make sure all entries have a valid string, while also finding strings which are unused.

**Comment by wadhwamatic** [comment]
Thanks @ericboucher and @Ry-DS. 

If I've understood correctly, with this approach we would need to mark every piece of text to be translated, create translation files, and figure out a plan for continued updates of those text components over time. That all sounds reasonable, and given that translation of text into local languages as a regular component of our work, not a major ask. 

I'm not so clear about how we would manage text which is specific to the configuration of a deployment, like the text captured in layers.json. We certainly shouldn't create a scenario where text specific to a country deployment would require a translation for another deployment which would not use the same text.

**Comment by wadhwamatic** [comment]
@ericboucher - we'd need to have some way to have the content that is within layers.json available in multiple languages. there will always be a need for the full UI to be available in English, in addition to local language(s)
